import React, { useEffect, useMemo, useRef, useState } from "react";

const EMOJIS = ["😀","😂","🤣","😍","😎","🔥","❤️","👍","🎉","☕","😄","😁","😅","😊","🤔","🙌","👏","💯","✨","🚀","🐶","🐱","🍔","🍕","⚽","🚗","💡","🎵","⭐","🌟","🙏"];
const RECENT_KEY = "hyperoom-recent-emoji-v1";

export function EmojiPicker({ onSelect, onClose }: { onSelect: (emoji: string) => void; onClose: () => void }): React.JSX.Element {
  const rootRef = useRef<HTMLDivElement | null>(null);
  const [recent, setRecent] = useState<string[]>(() => { try { const value = JSON.parse(localStorage.getItem(RECENT_KEY) ?? "[]"); return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string").slice(0, 8) : []; } catch { return []; } });
  const items = useMemo(() => [...recent, ...EMOJIS.filter((emoji) => !recent.includes(emoji))], [recent]);
  const [focusIndex, setFocusIndex] = useState(0);
  useEffect(() => { const outside = (event: MouseEvent) => { if (rootRef.current && !rootRef.current.contains(event.target as Node)) onClose(); }; const key = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); if (event.key === "ArrowRight") setFocusIndex((value) => Math.min(value + 1, items.length - 1)); if (event.key === "ArrowLeft") setFocusIndex((value) => Math.max(value - 1, 0)); if (event.key === "ArrowDown") setFocusIndex((value) => Math.min(value + 8, items.length - 1)); if (event.key === "ArrowUp") setFocusIndex((value) => Math.max(value - 8, 0)); if (event.key === "Enter") document.querySelector<HTMLButtonElement>(`[data-emoji-index="${focusIndex}"]`)?.click(); }; document.addEventListener("mousedown", outside); document.addEventListener("keydown", key); return () => { document.removeEventListener("mousedown", outside); document.removeEventListener("keydown", key); }; }, [focusIndex, items.length, onClose]);
  function choose(emoji: string) { const next = [emoji, ...recent.filter((item) => item !== emoji)].slice(0, 8); setRecent(next); localStorage.setItem(RECENT_KEY, JSON.stringify(next)); onSelect(emoji); onClose(); }
  return <div className="emoji-picker" ref={rootRef} role="dialog" aria-label="Emoji picker"><div className="emoji-picker-title"><strong>Emoji</strong><button type="button" onClick={onClose} aria-label="Close emoji picker">×</button></div>{recent.length > 0 && <div className="emoji-section"><small>Recently Used</small><div className="emoji-grid">{recent.map((emoji, index) => <button key={`recent-${emoji}`} type="button" data-emoji-index={index} className={focusIndex === index ? "focused" : ""} aria-label={`Use ${emoji}`} onClick={() => choose(emoji)}>{emoji}</button>)}</div></div>}<div className="emoji-section"><small>Emoji</small><div className="emoji-grid">{EMOJIS.filter((emoji) => !recent.includes(emoji)).map((emoji, index) => { const offset = recent.length + index; return <button key={emoji} type="button" data-emoji-index={offset} className={focusIndex === offset ? "focused" : ""} aria-label={`Use ${emoji}`} onClick={() => choose(emoji)}>{emoji}</button>; })}</div></div></div>;
}
