import React, { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import { createAuthApi, createHyperoomClientFromEnv, createHyperoomRepository, createPresenceApi, type AuthApi, type HyperoomRepository, type PresenceApi } from "@hyperoom/data";
import { createHyperoomChatEngine, type HyperoomChatEngine } from "@hyperoom/chat-engine";
import { type ClientCommandEngine, type CommandResult } from "@hyperoom/irc-engine";
import type { HyperoomMessage, HyperoomProfile, HyperoomRoom, HyperoomRoomMemberProfile } from "@hyperoom/shared";
import { createHyperoomCommandEngine } from "./hyperoom-command-engine";
import { GlobalOnline, RoomStateLabel } from "./presence-view";
import { InvitationInbox, RoomAccessPanel } from "./room-access";
import "./styles.css";

const supabaseConfig = { VITE_SUPABASE_URL: import.meta.env.VITE_SUPABASE_URL as string | undefined, VITE_SUPABASE_PUBLISHABLE_KEY: import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined };
type Session = Awaited<ReturnType<AuthApi["getSession"]>>;
type AuthMode = "sign-in" | "sign-up";
type LocalNotice = { id: string; kind: "SYSTEM_EVENT" | "ERROR"; content: string };
function friendlyError(error: unknown): string { return error instanceof Error ? error.message : "An unexpected error occurred."; }
function createServices(): { auth: AuthApi; repository: HyperoomRepository; presence: PresenceApi } | null {
  if (!supabaseConfig.VITE_SUPABASE_URL || !supabaseConfig.VITE_SUPABASE_PUBLISHABLE_KEY) return null;
  const client = createHyperoomClientFromEnv(supabaseConfig); return { auth: createAuthApi(client), repository: createHyperoomRepository(client), presence: createPresenceApi(client) };
}
const services = createServices();

function AuthScreen({ auth }: { auth: AuthApi }): React.JSX.Element {
  const [mode, setMode] = useState<AuthMode>("sign-in"); const [nickname, setNickname] = useState(""); const [phone, setPhone] = useState(""); const [password, setPassword] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(null); try { if (mode === "sign-in") await auth.signIn(nickname, password); else await auth.signUp(phone, password, nickname, nickname); } catch (e) { setError(friendlyError(e)); } finally { setBusy(false); } }
  return <main className="auth-shell"><section className="auth-card"><div className="brand-mark">H</div><p className="eyebrow">HYPEROOM - REAL CORE</p><h1>{mode === "sign-in" ? "Welcome back" : "Create your account"}</h1><p className="muted">One door for everyone. Your account role is determined by Hyperoom.</p><form onSubmit={submit} className="stack"><label>{mode === "sign-in" ? "Nickname / Phone number" : "Nickname"}<input value={nickname} onChange={(e) => setNickname(e.target.value)} required minLength={2} maxLength={24} /></label>{mode === "sign-up" && <label>Phone number<input type="tel" value={phone} onChange={(e) => setPhone(e.target.value)} required /></label>}<label>Password<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} required minLength={8} /></label>{error && <div className="error-box">{error}</div>}<button className="primary-button" disabled={busy}>{busy ? "Connecting..." : mode === "sign-in" ? "Sign in" : "Create account"}</button></form><button className="link-button" onClick={() => { setMode(mode === "sign-in" ? "sign-up" : "sign-in"); setError(null); }}>{mode === "sign-in" ? "Need an account? Create one" : "Already have an account? Sign in"}</button></section></main>;
}

function ProfileBootstrap({ repository, session, onReady }: { repository: HyperoomRepository; session: NonNullable<Session>; onReady: (profile: HyperoomProfile) => void }): React.JSX.Element {
  const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  useEffect(() => { let cancelled = false; void (async () => { try { const existing = await repository.getProfile(session.user.id); if (existing) { if (!cancelled) onReady(existing); return; } const metadata = session.user.user_metadata as Record<string, unknown> | undefined; const metadataUsername = typeof metadata?.username === "string" ? metadata.username : ""; const suffix = session.user.phone?.replace(/\D/g, "").slice(-8) || "user"; const base = (metadataUsername || `user_${suffix}`).toLowerCase().replace(/[^a-z0-9_]/g, "_").slice(0, 24) || "user"; setSaving(true); const created = await repository.upsertProfile({ id: session.user.id, username: base, displayName: typeof metadata?.display_name === "string" ? metadata.display_name : metadataUsername || base }); if (!cancelled) onReady(created); } catch (e) { if (!cancelled) setError(friendlyError(e)); } finally { if (!cancelled) setSaving(false); } })(); return () => { cancelled = true; }; }, [onReady, repository, session.user.id, session.user.user_metadata]);
  return <main className="center-shell"><section className="status-card"><div className="spinner" /><h2>{saving ? "Creating your profile..." : "Loading your profile..."}</h2>{error && <div className="error-box">{error}</div>}</section></main>;
}

function RoomSidebar({ repository, rooms, activeRoom, onlineCounts, onSelect, onRooms }: { repository: HyperoomRepository; rooms: HyperoomRoom[]; activeRoom: HyperoomRoom | null; onlineCounts: Record<string, number>; onSelect: (room: HyperoomRoom) => void; onRooms: (rooms: HyperoomRoom[]) => void }): React.JSX.Element {
  const [name, setName] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  async function createRoom(event: React.FormEvent) { event.preventDefault(); const normalized = name.trim().replace(/^#/, ""); if (!normalized) return; setBusy(true); setError(null); try { const room = await repository.createRoom({ name: normalized, type: "public" }); onRooms([...rooms.filter((item) => item.id !== room.id), room].sort((a, b) => a.name.localeCompare(b.name))); onSelect(room); setName(""); } catch (e) { setError(friendlyError(e)); } finally { setBusy(false); } }
  async function selectRoom(room: HyperoomRoom) { setError(null); try { await repository.joinRoom(room.id); onSelect(room); } catch (e) { setError(friendlyError(e)); } }
  return <aside className="room-sidebar"><div className="sidebar-heading"><div><span className="eyebrow">CHANNELS</span><h2>Rooms</h2></div><span className="room-count">{rooms.length}</span></div><form className="create-room" onSubmit={createRoom}><input value={name} onChange={(e) => setName(e.target.value)} placeholder="# new-room" aria-label="New room name" /><button disabled={busy} title="Create room">+</button></form>{error && <div className="sidebar-error">{error}</div>}<div className="room-list">{rooms.map((room) => <button key={room.id} className={`room-item ${activeRoom?.id === room.id ? "active" : ""}`} onClick={() => void selectRoom(room)}><span>{room.isLocked ? "🔒" : "#"}</span><span className="room-name">{room.name}</span><RoomStateLabel room={room} count={onlineCounts[room.id] ?? 0} /></button>)}</div></aside>;
}

function renderMessage(message: HyperoomMessage, sender: HyperoomProfile | undefined): React.JSX.Element { const name = sender?.username ?? `user_${message.senderId.slice(0, 8)}`; if (message.kind === "action" || message.eventType === "action") return <span><strong>* {name}</strong> {message.content}</span>; return <span>{message.content}</span>; }

function ChatRoom({ repository, chatEngine, commandEngine, room, profile, onSelectRoom, onRoomUpdated, onProfileUpdated, onMembersUpdated, onPart }: { repository: HyperoomRepository; chatEngine: HyperoomChatEngine; commandEngine: ClientCommandEngine; room: HyperoomRoom; profile: HyperoomProfile; onSelectRoom: (room: HyperoomRoom) => void; onRoomUpdated: (room: HyperoomRoom) => void; onProfileUpdated: (profile: HyperoomProfile) => void; onMembersUpdated: (members: HyperoomRoomMemberProfile[]) => void; onPart: (roomId: string) => void }): React.JSX.Element {
  const [messages, setMessages] = useState<HyperoomMessage[]>([]); const [memberProfiles, setMemberProfiles] = useState<HyperoomRoomMemberProfile[]>([]); const [draft, setDraft] = useState(""); const [notices, setNotices] = useState<LocalNotice[]>([]); const [loading, setLoading] = useState(true); const [sending, setSending] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => { let cancelled = false; setLoading(true); setError(null); setMessages([]); setMemberProfiles([]); setNotices([]); void Promise.all([repository.listMessages(room.id), repository.listMemberProfiles(room.id)]).then(([items, members]) => { if (!cancelled) { setMessages(items); setMemberProfiles(members); onMembersUpdated(members); } }).catch((e) => { if (!cancelled) setError(friendlyError(e)); }).finally(() => { if (!cancelled) setLoading(false); }); const channel = repository.subscribeRoom(room.id, { onMessage: (message) => setMessages((current) => current.some((item) => item.id === message.id) ? current : [...current, message]), onMessageUpdated: (message) => setMessages((current) => current.map((item) => item.id === message.id ? message : item)), onMemberChange: () => { void repository.listMemberProfiles(room.id).then((items) => { setMemberProfiles(items); onMembersUpdated(items); }).catch((e) => setError(friendlyError(e))); }, onRoomChange: onRoomUpdated, onStatus: (status) => { if (status === "CHANNEL_ERROR" || status === "TIMED_OUT") setError("Realtime connection failed. Retrying may be required."); } }); return () => { cancelled = true; channel.unsubscribe(); }; }, [onMembersUpdated, onRoomUpdated, repository, room.id]);
  function addNotice(result: CommandResult) { if (!result.content) return; setNotices((current) => [...current, { id: crypto.randomUUID(), kind: result.kind === "ERROR" ? "ERROR" : "SYSTEM_EVENT", content: result.content ?? "" }]); }
  async function send(event: React.FormEvent) { event.preventDefault(); const content = draft.trim(); if (!content || sending) return; setSending(true); setError(null); try { const result = await commandEngine.execute(content, { currentRoom: room, nickname: profile.username }); if (result.kind === "MESSAGE") { const created = await chatEngine.sendMessage({ roomId: room.id, content: result.content ?? "" }); setMessages((current) => current.some((item) => item.id === created.id) ? current : [...current, created]); } else { const data = result.data as { action?: string; roomId?: string; profile?: HyperoomProfile } | undefined; if (data?.action === "clear-room" && data.roomId === room.id) { setMessages([]); setNotices([]); setError(null); } else addNotice(result); if (result.room) { onRoomUpdated(result.room); if ((result.data as { action?: string } | undefined)?.action === "switch-room") onSelectRoom(result.room); } if (data?.action === "part-room" && data.roomId) onPart(data.roomId); if (data?.action === "profile-updated" && data.profile) onProfileUpdated(data.profile); } setDraft(""); } catch (e) { setError(friendlyError(e)); } finally { setSending(false); } }
  const allMessages = [...messages.map((message) => ({ type: "message" as const, message })), ...notices.map((notice) => ({ type: "notice" as const, notice }))];
  return <section className="chat-room"><header className="chat-header"><div><div className="room-title">{room.isLocked ? "#" : "#"} {room.name}</div><div className="muted">{room.isLocked ? "LOCKED - Invite Only" : "PUBLIC"}{room.topic || room.description ? ` | ${room.topic || room.description}` : ""}</div></div><div className="chat-header-actions"><RoomAccessPanel repository={repository} room={room} profile={profile} members={memberProfiles} onRoomUpdated={onRoomUpdated}/><div className="connection-pill"><span /> LIVE</div></div></header><div className="message-list">{loading && <div className="empty-state">Loading messages...</div>}{!loading && !allMessages.length && <div className="empty-state"><strong>Room is empty.</strong><span>Send the first message.</span></div>}{allMessages.map((item) => { if (item.type === "notice") return <article className="message system-message" key={item.notice.id}><div className="message-body"><span className={item.notice.kind === "ERROR" ? "system-error" : "system-event"}>{item.notice.content}</span></div></article>; const message = item.message; const sender = message.senderId === profile.id ? profile : memberProfiles.find((member) => member.profile.id === message.senderId)?.profile; const displayName = sender?.displayName ?? `User ${message.senderId.slice(0, 8)}`; if (message.kind === "system") return <article className="message system-message" key={message.id}><div className="message-body"><span className="system-event">{message.content}</span><time>{new Date(message.createdAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</time></div></article>; return <article className={"message " + (message.senderId === profile.id ? "mine" : "")} key={message.id}><div className="message-avatar">{displayName.slice(0, 1).toUpperCase()}</div><div><div className="message-meta"><strong>{displayName}</strong>{sender && <small>@{sender.username}</small>}<time>{new Date(message.createdAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</time></div><div className="message-body">{message.deletedAt ? <em>message deleted</em> : renderMessage(message, sender)}{message.editedAt && !message.deletedAt && <small> (edited)</small>}</div></div></article>; })}</div><form className="composer" onSubmit={send}><input value={draft} onChange={(e) => setDraft(e.target.value)} placeholder={`Message #${room.name} or /command`} disabled={sending} aria-label="Message or command" /><button className="send-button" disabled={sending || !draft.trim()}>{sending ? "..." : "Send"}</button></form>{error && <div className="chat-error">{error}</div>}</section>;
}

function MemberSidebar({ members, viewer }: { members: HyperoomRoomMemberProfile[]; viewer: HyperoomProfile }): React.JSX.Element {
  const groups = [{ key: "owner", label: "OWNER" }, { key: "admin", label: "ADMIN" }, { key: "moderator", label: "MODERATOR" }, { key: "voice", label: "VOICE" }, { key: "member", label: "MEMBERS" }];
  function effectiveRole(item: HyperoomRoomMemberProfile) { if (item.profile.systemRole !== "member") return item.profile.systemRole; return item.role === "voice" ? "voice" : "member"; }
  return <aside className="member-sidebar"><div className="member-heading"><span className="eyebrow">MEMBERS</span><strong>{members.length}</strong></div>{groups.map((group) => { const items = members.filter((item) => effectiveRole(item) === group.key); if (!items.length) return null; return <section className="member-group" key={group.key}><div className="member-group-title">{group.label}</div>{items.map((item) => <div className={"member-row " + (item.profile.id === viewer.id ? "current-user" : "")} key={item.userId}><div className="member-avatar">{item.profile.displayName.slice(0, 1).toUpperCase()}</div><div className="member-copy"><strong>{item.profile.displayName}</strong><span>@{item.profile.username}</span></div>{item.role === "owner" && <span className="owner-badge">ROOM OWNER</span>}</div>)}</section>; })}</aside>;
}

function Workspace({ auth, repository, presence, session }: { auth: AuthApi; repository: HyperoomRepository; presence: PresenceApi; session: NonNullable<Session> }): React.JSX.Element {
  const chatEngine = useMemo(() => createHyperoomChatEngine(repository), [repository]);
  const [profile, setProfile] = useState<HyperoomProfile | null>(null); const [memberProfiles, setMemberProfiles] = useState<HyperoomRoomMemberProfile[]>([]); const [rooms, setRooms] = useState<HyperoomRoom[]>([]); const [activeRoom, setActiveRoom] = useState<HyperoomRoom | null>(null); const [loadingRooms, setLoadingRooms] = useState(false); const [error, setError] = useState<string | null>(null); const [globalOnline, setGlobalOnline] = useState(0); const [onlineCounts, setOnlineCounts] = useState<Record<string, number>>({});
  const roomPresenceRef = useRef(new Map<string, ReturnType<PresenceApi["subscribeRoomPresence"]>>()); const activePresenceRoomRef = useRef<string | null>(null); const activeRoomRef = useRef<HyperoomRoom | null>(null); activeRoomRef.current = activeRoom;
  const onProfileReady = useCallback((next: HyperoomProfile) => setProfile(next), []);
  const commandEngine = useMemo(() => profile ? createHyperoomCommandEngine({ repository, auth, getProfile: () => profile }) : null, [auth, profile, repository]);
  const handleRoomUpdated = useCallback((next: HyperoomRoom) => { setActiveRoom(next); setRooms((current) => current.map((item) => item.id === next.id ? next : item)); }, []);
  const handleProfileUpdated = useCallback((next: HyperoomProfile) => { setProfile(next); setMemberProfiles((current) => current.map((item) => item.userId === next.id ? { ...item, profile: next } : item)); }, []);
  useEffect(() => { if (!profile) return; let cancelled = false; setLoadingRooms(true); setError(null); const applyRooms = (items: HyperoomRoom[]) => { if (cancelled) return; setRooms(items); setActiveRoom((current) => current && items.some((item) => item.id === current.id) ? current : items[0] ?? null); }; void repository.listPublicRooms().then(applyRooms).catch((e) => { if (!cancelled) setError(friendlyError(e)); }).finally(() => { if (!cancelled) setLoadingRooms(false); }); const channel = repository.subscribePublicRooms(applyRooms); return () => { cancelled = true; channel.unsubscribe(); }; }, [profile, repository]);
  useEffect(() => { if (!profile) return; const global = presence.subscribeGlobalPresence(profile.id, setGlobalOnline, (status) => { if (status === "CHANNEL_ERROR" || status === "TIMED_OUT") setError("Global presence connection failed."); }); return () => { void presence.untrackRoom(global); global.unsubscribe(); }; }, [presence, profile]);
  useEffect(() => { if (!profile) return; const map = roomPresenceRef.current; const wanted = new Set(rooms.map((room) => room.id)); for (const [roomId, channel] of map) { if (!wanted.has(roomId)) { void presence.untrackRoom(channel); channel.unsubscribe(); map.delete(roomId); setOnlineCounts((current) => { const next = { ...current }; delete next[roomId]; return next; }); } } for (const room of rooms) { if (map.has(room.id)) continue; const channel = presence.subscribeRoomPresence(room.id, profile.id, (count) => setOnlineCounts((current) => ({ ...current, [room.id]: count })), (status) => { if (status === "CHANNEL_ERROR" || status === "TIMED_OUT") setOnlineCounts((current) => ({ ...current, [room.id]: 0 })); if (status === "SUBSCRIBED" && activeRoomRef.current?.id === room.id) void presence.trackRoom(channel, room.id, profile.id); }); map.set(room.id, channel); } return () => {}; }, [presence, profile, rooms]);
  useEffect(() => { const previous = activePresenceRoomRef.current; if (previous && previous !== activeRoom?.id) { const oldChannel = roomPresenceRef.current.get(previous); if (oldChannel) void presence.untrackRoom(oldChannel); } activePresenceRoomRef.current = activeRoom?.id ?? null; if (activeRoom) { const channel = roomPresenceRef.current.get(activeRoom.id); if (channel) { if ((channel as unknown as { state?: string }).state === "joined") void presence.trackRoom(channel, activeRoom.id, profile?.id ?? ""); else setTimeout(() => { if (activeRoomRef.current?.id === activeRoom.id && profile) void presence.trackRoom(channel, activeRoom.id, profile.id); }, 250); } } return () => {}; }, [activeRoom, presence, profile]);
  useEffect(() => () => { for (const channel of roomPresenceRef.current.values()) { void presence.untrackRoom(channel); channel.unsubscribe(); } roomPresenceRef.current.clear(); }, [presence]);
  if (!profile) return <ProfileBootstrap repository={repository} session={session} onReady={onProfileReady}/>;
  async function signOut() { try { await auth.signOut(); } catch (e) { setError(friendlyError(e)); } }
  function selectAfterPart(roomId: string) { const next = rooms.find((item) => item.id !== roomId) ?? null; setMemberProfiles([]); setActiveRoom(next); }
  return <main className="workspace"><header className="topbar"><div className="brand"><div className="brand-mark small">H</div><div><strong>Hyperoom</strong><span>mIRC DNA - native core</span></div></div><div className="user-area"><GlobalOnline count={globalOnline}/><InvitationInbox repository={repository} profile={profile} onOpenRoom={(room) => { setRooms((current) => current.some((item) => item.id === room.id) ? current.map((item) => item.id === room.id ? room : item) : [...current, room].sort((a, b) => a.name.localeCompare(b.name))); setActiveRoom(room); }}/ ><div className={`system-role-badge ${profile.systemRole}`}>{profile.systemRole === "owner" ? "OWNER" : profile.systemRole.toUpperCase()}</div><div className="user-avatar">{profile.displayName.slice(0, 1).toUpperCase()}</div><div className="user-copy"><strong>{profile.displayName}</strong><span>@{profile.username}</span></div><button className="ghost-button" onClick={() => void signOut()}>Sign out</button></div></header><div className="workspace-body"><RoomSidebar repository={repository} rooms={rooms} activeRoom={activeRoom} onlineCounts={onlineCounts} onSelect={setActiveRoom} onRooms={setRooms}/><section className="main-panel">{error && <div className="global-error">{error}</div>}{loadingRooms ? <div className="empty-panel">Loading rooms...</div> : activeRoom && commandEngine ? <ChatRoom repository={repository} chatEngine={chatEngine} commandEngine={commandEngine} room={activeRoom} profile={profile} onSelectRoom={setActiveRoom} onRoomUpdated={handleRoomUpdated} onProfileUpdated={handleProfileUpdated} onMembersUpdated={setMemberProfiles} onPart={selectAfterPart}/> : <div className="empty-panel"><div className="empty-icon">#</div><h2>No room yet</h2><p>Create or join a public channel from the sidebar.</p></div>}</section><MemberSidebar members={memberProfiles} viewer={profile}/></div></main>;
}

function App(): React.JSX.Element {
  const [session, setSession] = useState<Session>(null); const [loading, setLoading] = useState(Boolean(services)); const [error, setError] = useState<string | null>(null);
  useEffect(() => { if (!services) return; let mounted = true; void services.auth.getSession().then((next) => { if (mounted) setSession(next); }).catch((e) => { if (mounted) setError(friendlyError(e)); }).finally(() => { if (mounted) setLoading(false); }); const unsubscribe = services.auth.onAuthStateChange((_event, next) => setSession(next)); return () => { mounted = false; unsubscribe(); }; }, []);
  if (!services) return <main className="config-shell"><section className="config-card"><p className="eyebrow">HYPEROOM CONFIGURATION</p><h1>Connect Supabase</h1><p>Real authentication and chat are enabled, but this build has no browser-safe Supabase environment variables.</p></section></main>;
  if (loading) return <main className="center-shell"><section className="status-card"><div className="spinner"/><h2>Connecting to Hyperoom...</h2><p className="muted">Restoring your real Supabase session.</p></section></main>;
  if (error) return <main className="center-shell"><section className="status-card"><h2>Connection error</h2><div className="error-box">{error}</div></section></main>;
  if (!session) return <AuthScreen auth={services.auth}/>;
  return <Workspace auth={services.auth} repository={services.repository} presence={services.presence} session={session}/>;
}

createRoot(document.getElementById("root")!).render(<React.StrictMode><App /></React.StrictMode>);
