import { useEffect, useState } from "react";

type N={id:string;type:string;title:string;body:string;created_at:string;read_at:string|null;room_id:string|null};
const keyBytes=(s:string)=>Uint8Array.from(atob(s.replace(/-/g,"+").replace(/_/g,"/")+"=".repeat((4-s.length%4)%4)),c=>c.charCodeAt(0));
export function NotificationCenter({client,profileId}:{client:any;profileId:string}):React.JSX.Element{
 const db=client;
 const [rows,setRows]=useState<N[]>([]),[open,setOpen]=useState(false),[push,setPush]=useState(true),[sound,setSound]=useState(true),[busy,setBusy]=useState(false);
 const unread=rows.filter(x=>!x.read_at).length;
 useEffect(()=>{let dead=false;void Promise.all([
  db.from("notifications").select("id,type,title,body,created_at,read_at,room_id").order("created_at",{ascending:false}).limit(50),
  db.from("notification_preferences").select("push_enabled,sound_enabled").eq("user_id",profileId).maybeSingle()
 ]).then(([n,p]:any[])=>{if(dead)return;if(!n.error)setRows(n.data??[]);if(!p.error&&p.data){setPush(p.data.push_enabled);setSound(p.data.sound_enabled)}});return()=>{dead=true}},[db,profileId]);
 useEffect(()=>{const c=db.channel("notify:"+profileId).on("postgres_changes",{event:"INSERT",schema:"public",table:"notifications",filter:`recipient_user_id=eq.${profileId}`},(e:any)=>{const n=e.new as N;setRows(x=>[n,...x.filter(y=>y.id!==n.id)].slice(0,50));if(sound&&document.visibilityState==="visible")try{const a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.frequency.value=880;g.gain.value=.035;o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+.09)}catch{}}).subscribe();return()=>{void db.removeChannel(c)}},[db,profileId,sound]); async function enable(){setBusy(true);try{if(!("serviceWorker"in navigator)||!("PushManager"in window))throw Error("Browser ini tidak mendukung push notifikation.");if(await Notification.requestPermission()!=="granted")throw Error("Izin notifikasi tidak diberikan.");const r=await navigator.serviceWorker.register("/sw.js"),k=await fetch("/api/notifications-config").then(x=>x.json());if(!k.publicKey)throw Error("Push configuration tidak tersedia.");const old=await r.pushManager.getSubscription(),s=old??await r.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:keyBytes(k.publicKey) as any}),j=s.toJSON();await db.from("push_subscriptions").upsert({user_id:profileId,endpoint:j.endpoint,p256dh:j.keys?.p256dh,auth:j.keys?.auth,user_agent:navigator.userAgent,disabled_at:null,updated_at:new Date().toISOString()},{onConflict:"endpoint"});await db.from("notification_preferences").upsert({user_id:profileId,push_enabled:true,sound_enabled:sound},{onConflict:"user_id"});setPush(true)}catch(e){alert(e instanceof Error?e.message:"Gagal mengaktifkan notifikasi")}finally{setBusy(false)}}
 async function read(id:string){const now=new Date().toISOString();setRows(x=>x.map(n=>n.id===id?{...n,read_at:now}:n));await db.from("notifications").update({read_at:now}).eq("id",id).eq("recipient_user_id",profileId)}
 async function readAll(){const now=new Date().toISOString();setRows(x=>x.map(n=>({...n,read_at:n.read_at??now})));await db.from("notifications").update({read_at:now}).eq("recipient_user_id",profileId).is("read_at",null)}
 async function toggleSound(){const v=!sound;setSound(v);await db.from("notification_preferences").upsert({user_id:profileId,push_enabled:push,sound_enabled:v},{onConflict:"user_id"})}
 return <div className="notification-center"><button className="notification-trigger" type="button" onClick={()=>setOpen(x=>!x)}>🔔{unread>0&&<span className="notification-badge">{unread>99?"99+":unread}</span>}</button>{open&&<div className="notification-panel"><div className="notification-panel-head"><strong>Notifications</strong><span><button type="button" onClick={()=>void toggleSound()}>{sound?"🔊":"🔇"}</button><button type="button" disabled={!unread} onClick={()=>void readAll()}>Read all</button></span></div><button className="notification-push-button" type="button" disabled={busy} onClick={()=>void enable()}>{busy?"Enabling...":push?"✓ Device notifications enabled":"Enable device notifications"}</button><div className="notification-list">{rows.length===0&&<div className="notification-empty">No notifications yet.</div>}{rows.map(n=><button className={"notification-item "+(n.read_at?"read":"unread")} key={n.id} type="button" onClick={()=>{void read(n.id);setOpen(false);if(n.room_id)void db.from("rooms").select("id,name").eq("id",n.room_id).maybeSingle().then((r:any)=>{ if(r.data) window.dispatchEvent(new CustomEvent("hyperoom-open-room",{detail:r.data.id})); })}}><span>●</span><span><strong>{n.title}</strong><em>{n.body}</em><small>{new Date(n.created_at).toLocaleString()}</small></span></button>)}</div></div>}</div>
}
